
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const LoanApplication = lazy(() => import("./pages/LoanApplication.tsx"));
const LoanApproved = lazy(() => import("./pages/LoanApproved.tsx"));
const LoanSuccess = lazy(() => import("./pages/LoanSuccess.tsx"));
const LoanUnderReview = lazy(() => import("./pages/LoanUnderReview.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/loan-application", element: <UserGuard><LoanApplication /></UserGuard>},
	{ path: "/loanapplication", element: <UserGuard><LoanApplication /></UserGuard>},
	{ path: "/loan-approved", element: <UserGuard><LoanApproved /></UserGuard>},
	{ path: "/loanapproved", element: <UserGuard><LoanApproved /></UserGuard>},
	{ path: "/loan-success", element: <UserGuard><LoanSuccess /></UserGuard>},
	{ path: "/loansuccess", element: <UserGuard><LoanSuccess /></UserGuard>},
	{ path: "/loan-under-review", element: <UserGuard><LoanUnderReview /></UserGuard>},
	{ path: "/loanunderreview", element: <UserGuard><LoanUnderReview /></UserGuard>},

];
